schema_version: 1

context:
  name: azure-cli
  version: "2.74.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure_cli-${{ version }}.tar.gz
  sha256: 28b938246f0a2099e378c60ea22e2931fec2226f3f44e2a98b1895521b85540a

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - antlr4-python3-runtime >=4.13.1,<4.14.dev0
    - azure-appconfiguration >=1.7.0,<1.8.dev0
    - azure-batch >=15.0.0b1,<15.1.dev0
    - azure-cli-core ==${{ version }}
    - azure-cosmos >=3.0,<4.dev0,>=3.0.2
    - azure-data-tables ==12.4.0
    - azure-datalake-store >=1.0.0a0,<1.1.dev0
    - azure-keyvault-administration ==4.4.0b2
    - azure-keyvault-certificates ==4.7.0
    - azure-keyvault-keys ==4.11.0b1
    - azure-keyvault-secrets ==4.7.0
    - azure-keyvault-securitydomain ==1.0.0b1
    - azure-mgmt-advisor ==9.0.0
    - azure-mgmt-apimanagement ==4.0.0
    - azure-mgmt-appconfiguration ==3.1.0
    - azure-mgmt-appcontainers ==2.0.0
    - azure-mgmt-applicationinsights >=1.0.0,<1.1.dev0
    - azure-mgmt-authorization >=4.0.0,<4.1.dev0
    - azure-mgmt-batchai ==7.0.0b1
    - azure-mgmt-batch >=17.3.0,<17.4.dev0
    - azure-mgmt-billing ==6.0.0
    - azure-mgmt-botservice >=2.0.0b3,<2.1.dev0
    - azure-mgmt-cdn ==12.0.0
    - azure-mgmt-cognitiveservices >=13.5.0,<13.6.dev0
    - azure-mgmt-compute >=34.1.0,<34.2.dev0
    - azure-mgmt-containerinstance ==10.2.0b1
    - azure-mgmt-containerregistry ==14.0.0
    - azure-mgmt-containerservice >=36.0.0,<37.0.dev0
    - azure-mgmt-cosmosdb ==9.8.0
    - azure-mgmt-databoxedge >=1.0.0,<1.1.dev0
    - azure-mgmt-datalake-store >=1.1.0b1,<1.2.dev0
    - azure-mgmt-datamigration >=10.0.0,<10.1.dev0
    - azure-mgmt-dns >=8.0.0,<8.1.dev0
    - azure-mgmt-eventgrid ==10.2.0b2
    - azure-mgmt-eventhub >=10.1.0,<10.2.dev0
    - azure-mgmt-extendedlocation ==1.0.0b2
    - azure-mgmt-hdinsight ==9.0.0b3
    - azure-mgmt-imagebuilder >=1.3.0,<1.4.dev0
    - azure-mgmt-iotcentral >=10.0.0b1,<10.1.dev0
    - azure-mgmt-iothub ==3.0.0
    - azure-mgmt-iothubprovisioningservices ==1.1.0
    - azure-mgmt-keyvault ==11.0.0
    - azure-mgmt-loganalytics ==13.0.0b4
    - azure-mgmt-managementgroups >=1.0.0,<1.1.dev0
    - azure-mgmt-maps >=2.0.0,<2.1.dev0
    - azure-mgmt-marketplaceordering ==1.1.0
    - azure-mgmt-media >=9.0,<10.dev0
    - azure-mgmt-monitor >=7.0.0b1,<7.1.dev0
    - azure-mgmt-msi >=7.0.0,<7.1.dev0
    - azure-mgmt-netapp >=10.1.0,<10.2.dev0
    - azure-mgmt-policyinsights ==1.1.0b4
    - azure-mgmt-postgresqlflexibleservers ==1.1.0b2
    - azure-mgmt-privatedns >=1.0.0,<1.1.dev0
    - azure-mgmt-rdbms ==10.2.0b17
    - azure-mgmt-mysqlflexibleservers ==1.0.0b3
    - azure-mgmt-recoveryservicesbackup >=9.2.0,<9.3.dev0
    - azure-mgmt-recoveryservices >=3.0.0,<3.1.dev0
    - azure-mgmt-redhatopenshift >=1.5.0,<1.6.dev0
    - azure-mgmt-redis >=14.5.0,<14.6.dev0
    - azure-mgmt-resource ==23.3.0
    - azure-mgmt-search >=9.0,<10.dev0
    - azure-mgmt-security ==6.0.0
    - azure-mgmt-servicebus >=8.2.0,<8.3.dev0
    - azure-mgmt-servicefabricmanagedclusters ==2.1.0b1
    - azure-mgmt-servicelinker ==1.2.0b3
    - azure-mgmt-servicefabric >=2.1.0,<2.2.dev0
    - azure-mgmt-signalr ==2.0.0b2
    - azure-mgmt-sqlvirtualmachine ==1.0.0b5
    - azure-mgmt-sql ==4.0.0b21
    - azure-mgmt-storage ==23.0.0
    - azure-mgmt-synapse ==2.1.0b5
    - azure-mgmt-trafficmanager >=1.0.0,<1.1.dev0
    - azure-mgmt-web ==7.3.1
    - azure-monitor-query ==1.2.0
    - azure-multiapi-storage ==1.4.0
    - azure-storage-common >=1.4,<2.dev0
    - azure-synapse-accesscontrol >=0.5.0,<0.6.dev0
    - azure-synapse-artifacts >=0.20.0,<0.21.dev0
    - azure-synapse-managedprivateendpoints >=0.4.0,<0.5.dev0
    - azure-synapse-spark >=0.7.0,<0.8.dev0
    - chardet >=5.2.0,<5.3.dev0
    - colorama >=0.4.4,<0.5.dev0
    - distro
    - fabric >=3.2.2,<3.3.dev0
    - javaproperties >=0.5.1,<0.6.dev0
    - jsondiff >=2.0.0,<2.1.dev0
    - packaging >=20.9
    - paramiko >=2.0.8,<4.0.0
    - pycomposefile >=0.0.32
    - pygithub >=1.38,<2.dev0
    - pynacl >=1.5.0,<1.6.dev0
    - scp >=0.13.2,<0.14.dev0
    - semver >=3.0,<4.0.dev0
    - setuptools
    - six >=1.10.0
    - sshtunnel >=0.1.4,<0.2.dev0
    - tabulate
    - urllib3
    - websocket-client >=1.3.1,<1.4.dev0
    - xmltodict >=0.12,<1.dev0
tests:
  - python:
      imports:
        - azure.cli.command_modules
        - azure.cli.command_modules.acr
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - if: unix
        then:
          - az --version
    # Windows needs more time to release the file lock.
    # Test failed: failed to remove directory `D:\bld\test\test_azure-cli74psTt`: The process cannot access the file because it is being used byanother process. (os error 32)
      - if: win
        then:
          - az --version && sleep 5

about:
  summary: Microsoft Azure Command-Line Tools
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/Azure/azure-cli

extra:
  recipe-maintainers:
    - janjagusch
